services:
  api-gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"

  identity-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8080"

  billing-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5002:8080"

  webhook-service:
    environment:
      NODE_ENV: development
    ports:
      - "5003:3000"

  travel-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5004:8080"

  postgres:
    ports:
      - "5432:5432"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"
