// <auto-generated />
using System;
using GeoLeadsService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoLeadsService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeoLeadsDbContext))]
    partial class GeoLeadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.GeoAreaQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Polygon>("Geometry")
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geometry_json");

                    b.Property<string>("RankingMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ranking_mode");

                    b.Property<string>("RequestedLeadTypesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_lead_types_json");

                    b.Property<int>("RequestedLimit")
                        .HasColumnType("integer")
                        .HasColumnName("requested_limit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("geo_area_queries", (string)null);
                });

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.GeoAreaQueryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<Guid>("GeoAreaQueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("geo_area_query_id");

                    b.Property<Guid>("GeoLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("geo_lead_id");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("LeadType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lead_type");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("text")
                        .HasColumnName("primary_email");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("text")
                        .HasColumnName("primary_phone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("ReasoningJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasoning_json");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sources_json");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("GeoAreaQueryId");

                    b.ToTable("geo_area_query_results", (string)null);
                });

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.LeadSourceIngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("fetched_count");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("lead_source_ingestion_runs", (string)null);
                });

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.LeadSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("RawAddress")
                        .HasColumnType("text")
                        .HasColumnName("raw_address");

                    b.Property<string>("RawCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_category");

                    b.Property<string>("RawEmail")
                        .HasColumnType("text")
                        .HasColumnName("raw_email");

                    b.Property<decimal?>("RawLatitude")
                        .HasColumnType("numeric")
                        .HasColumnName("raw_latitude");

                    b.Property<decimal?>("RawLongitude")
                        .HasColumnType("numeric")
                        .HasColumnName("raw_longitude");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_name");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload_json");

                    b.Property<string>("RawPhone")
                        .HasColumnType("text")
                        .HasColumnName("raw_phone");

                    b.Property<string>("RawWebsite")
                        .HasColumnType("text")
                        .HasColumnName("raw_website");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("SourceName", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("lead_source_records", (string)null);
                });

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.SavedGeoArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Polygon>("Geometry")
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geometry_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("saved_geo_areas", (string)null);
                });

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.GeoAreaQueryResult", b =>
                {
                    b.HasOne("GeoLeadsService.Domain.Aggregates.GeoAreaQuery", null)
                        .WithMany("Results")
                        .HasForeignKey("GeoAreaQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoLeadsService.Domain.Aggregates.GeoAreaQuery", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
